### ISSUE TITLE
Hot reloading not working

### ISSUE THREAD

**Issue by Hum4n01d** [mpontus/create-react-app-hot-loader#1]
Is this project still being maintained? I’m getting a full page reload when I try and run the app.

**Comment by Hum4n01d** [comment]
I just took the code from the latest create-react-app and then changed the start script like you said in the readme

**Comment by mpontus** [comment]
Create-react-app creates a project that is not aware of the hot reloading capabilities of your dev server. 
To activate hot reloading in your client, you also need to add *react-hot-loader@next* to your dev dependencies:

```bash
$ npm add --dev react-hot-loader@next
```


 and change src/index.js as follows:

```diff
 import React from 'react';
 import ReactDOM from 'react-dom';
+import { AppContainer } from 'react-hot-loader';
 import App from './App';
 import registerServiceWorker from './registerServiceWorker';
 import './index.css';
 
 ReactDOM.render(<App />, document.getElementById('root'));
 registerServiceWorker();

+if (module.hot) {
+  module.hot.accept('./App', () => {
+    const NextApp = require('./App').default;
+    ReactDOM.render(
+      <AppContainer>
+        <NextApp/>
+      </AppContainer>,
+      document.getElementById('root')
+    );
+  });
+}
```

I do have plans to continue development of this project, and your feedback is very welcome. 
Please let me know if this solves your issue, and I will try to improve documentation in the future.

**Comment by mpontus** [comment]
Also, full reloads are indicative of the failures in the Hot Module Replacement process. You can debug those by turning off the fallback mechanism with `--hot-only` flag. Now instead of full page reloads you will be seeing failure details in the browser console.

**Comment by Hum4n01d** [comment]
Thank you very much! I will try that. I'm glad to hear that you're still working on this project. By the way, if you get a chance, what exactly does this package do internally?

**Comment by mpontus** [comment]
It starts the webpack-dev-server configured to support create-react-app folder structure and asset types. Actually, the configuration that powers it has been pulled straight out of react-scripts (create-react-app internals). The only difference is that here we inject `'react-hot-loader/patch'` to webpack entry scripts, and add `'react-hot-loader/babel'` to babel plugins.

**Comment by Hum4n01d** [comment]
Cool! Thanks for the quick response. I will likely use this next time I start a new project!
