### ISSUE TITLE
What does this package actually do?

### ISSUE THREAD

**Issue by Hum4n01d** [mpontus/create-react-app-hot-loader#2]
I don’t understand what this package does for me. To add HMR with a vanilla create-react-app generated app I can just change `index.js` to: 

(you shared this in #1)
```
import React from 'react';
import ReactDOM from 'react-dom';
+import { AppContainer } from 'react-hot-loader';
import App from './App';
import registerServiceWorker from './registerServiceWorker';
import './index.css';

ReactDOM.render(<App />, document.getElementById('root'));
registerServiceWorker();

+if (module.hot) {
+  module.hot.accept('./App', () => {
+    const NextApp = require('./App').default;
+    ReactDOM.render(
+      <AppContainer>
+        <NextApp/>
+      </AppContainer>,
+      document.getElementById('root')
+    );
+  });
+}
```

Then installing `react-hot-loader@next` and running the app with `react-scripts start`.

I have HMR fine without `create-react-app-hot-loader`

**Comment by mpontus** [comment]
React hot loader also requires a babel-plugin to be present.

https://github.com/gaearon/react-hot-loader/tree/master/docs#user-content-migrating-from-create-react-app

This project provides a replacement webpack dev sever, with all necessary babel configurations. It helps you avoid injecting if hot reloading is all you're after.

**Comment by Hum4n01d** [comment]
It works without that though :smile:

**Comment by mpontus** [comment]
It will be a relief if what you're saying is true. I will check this tomorrow, thanks.

**Comment by Hum4n01d** [comment]
What did you find? Strangely enough, I’m trying to use create-react-app on a new project and I can’t get `react-hot-loader` to work because of this:

```
React Hot Loader: It appears that "react-hot-loader/patch" did not run immediately before the app started. Make sure that it runs before any other code. For example, if you use Webpack, you can add "react-hot-loader/patch" as the very first item to the "entry" array in its config. Alternatively, you can add require("react-hot-loader/patch") as the very first line in the application code, before any other imports.
```

So looks like you actually do need the webpack config :smile:. Not sure why it was working before and not now

**Comment by Hum4n01d** [comment]
Ok, I think I figured it out. Looks like hot reloading works with just the app container but you need to change the webpack config to retain application state. This video was pretty helpful: https://www.youtube.com/watch?v=f-ctxG2qEps

**Comment by mpontus** [comment]
Excellent! Sorry about the delay, and thank you for this insight. 

Did you end up ejecting as advertised in the video?

**Comment by Hum4n01d** [comment]
I didn't end up ejecting, I ended up just using webpack hmr without React hot loader
